react-select:
  - versions: ^4 || >=5.0.0 <5.3.0
    commands: npm test
    peerDependencies:
      - 'react@17'
      - 'react-dom@17'
      - '@testing-library/react@12'
      - '@types/react@17'
  # Support for React 18 was introduced in 5.3.0
  - versions: '>=5.3.0 <5.5.0 || ^5.5.1' # 5.5.0 has a bug
    commands: npm test
